#!/bin/bash

set -ex

if [ $# -eq 0 ]; then
    CFLAGS='-g -O0 -DDEBUG'
    OUTPUT='bin/debug/re2d'
elif [ $1 = 'debug' ]; then
    CFLAGS='-g -O0 -DDEBUG'
    OUTPUT='bin/debug/re2d'
elif [ $1 = 'release' ]; then
    CFLAGS='-O3'
    OUTPUT='bin/release/re2d'
else
    echo "ERROR: Wrong usage, please enter either 'debug', 'release', or nothing."
    exit
fi

LINK_RAYLIB=`pkg-config --cflags --libs raylib`

CSTD=c99
CC=clang

FILES='src/main.c'

$CC -std=$CSTD $CFLAGS $LINK_RAYLIB -o $OUTPUT $FILES
